    - name: Install Android SDK + Build-tools
      run: |
        ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        mkdir cmdline-temp
        unzip tools.zip -d cmdline-temp
        mv cmdline-temp/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.1.8937393"

        # Copy SDK into project so Buildozer uses it
        cp -r $ANDROID_SDK_ROOT $GITHUB_WORKSPACE/android-sdk
